### ISSUE TITLE
Unify specs across UCI APIs

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/uci-apis#58]
For BotService response DTO conversion, we are getting responses from UCI API should be in the same format. like below

**Old Response**
```json
{
  "apiId": "api.search.internal?perPage=5&page=1&match=true&startingMessage=hitestingsurvey6april",
  "path": "/admin/bot/search/internal?perPage=5&page=1&match=true&startingMessage=hitestingsurvey6april",
  "apiVersion": "v1",
  "msgid": "aac4233f-7542-43a9-8044-9bf628b30ce5",
  "result": [
    {}
  ]
}
```

**New Response**
```json
{
  "apiId": "api.bot.search?perPage=5&page=1&match=true&startingMessage=hitestingsurvey6april",
  "path": "/admin/bot/search?perPage=5&page=1&match=true&startingMessage=hitestingsurvey6april",
  "apiVersion": "v1",
  "msgid": "bd747db3-1718-4af0-b7b5-8b2c379c8c92",
  "result": {
    "data": []
  }
}
```

Need to change below API's response : 

1. Get Bot Details by - botID: http://159.65.151.114:9999/admin/bot/6a29e4ec-fc45-4009-b6f5-aa4d24a5e54b

2. Get Adapter Details by - adapterId: http://159.65.151.114:9999/admin/adapter/6efa8087-0939-49ab-b8e5-5676e036c17b

3. Get Secret by - secretVariable: http://159.65.151.114:9999/admin/secret/nl-app-firebase-notification

**Comment by ChakshuGautam** [comment]
Both are different APIs so you can pick and choose whichever. The change was made to support the admin which needs `totalCount` as a variable - see [here](https://github.com/samagra-comms/uci-apis/blob/9e8eb3c84a28319453e255c836dee63d90189d09/v2/uci/src/modules/bot/bot.service.ts#L244), but UCI services don't require that so they use a different [function](https://github.com/samagra-comms/uci-apis/blob/9e8eb3c84a28319453e255c836dee63d90189d09/v2/uci/src/modules/bot/bot.service.ts#L195) so that the java code remains the same. This was to account for different consumers of the API.

**Comment by susheelvar** [comment]
Call to be taken on whether to unify APIs for web + app side. 
To be included in roadmap for development by @susheelvar

**Comment by susheelvar** [comment]
@chinmoy12c to plan approach for unified APIs for web and app side (and list pros and cons).

**Comment by geeky-abhishek** [comment]
PR is raised

**Comment by aakashyadav-kgp** [comment]
Closing this. Tracking FE progress in other ticket.
